import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {comparisonResult,authorizeComparison,comparisonEnabled,checkComparisonPersona,COMMON_PROMPT_HASH} from '../lib/james-canary/comparison.ts';
import {emptyIntake,applyTurn,receipt,PERSONA_ID,sha} from '../lib/james-canary/state.ts';
import {toolResult,seal,unseal} from '../lib/james-canary/server.ts';
function sample(){let s={id:'13f474ea-1325-49b2-a787-45420f28f94d',browserId:'test',clientLabel:'test',createdAt:'2026-09-29T18:00:00Z',revision:0,stateHash:'',personaId:PERSONA_ID,config:{promptHash:COMMON_PROMPT_HASH,configHash:'test',voiceId:'test',voiceName:'test'},state:'ACTIVE',turns:[],intake:emptyIntake(),receipts:[]};for(const [i,content] of ['My employer did not pay me for two weeks of work.','I want help getting my unpaid wages.'].entries()){const t={id:'visitor-'+i,role:'user',content};s=receipt(s,applyTurn(s,t),t);}return s;}
test('ON is the identical baseline result object and bytes',()=>{const r=toolResult(sample(),'STATUS');assert.equal(comparisonResult(r,'on'),r);assert.equal(JSON.stringify(comparisonResult(r,'on')),JSON.stringify(r));});
test('OFF removes next-question/stage directives without mutating ON',()=>{const r=toolResult(sample(),'STATUS'),before=JSON.stringify(r),off=comparisonResult(r,'off');assert.equal(JSON.stringify(r),before);assert.doesNotMatch(JSON.stringify(off),/next_question|READY_FOR_CORRECTABLE_SUMMARY|response_pattern|completion_language_allowed|Move to a different missing intent/);assert.deepEqual(off.handoff_readiness,r.handoff_readiness);assert.deepEqual(off.accepted_current_turn_notes,r.accepted_current_turn_notes);assert.deepEqual(off.contact_fields,r.contact_fields);assert.deepEqual(off.notes_receipt,r.notes_receipt);assert.deepEqual(off.conversation_guidance.intent_states,r.conversation_guidance.intent_states);assert.deepEqual(off.conversation_guidance.handoff_truth,r.conversation_guidance.handoff_truth);assert.deepEqual(off.conversation_guidance.date_authority,r.conversation_guidance.date_authority);assert.deepEqual(off.conversation_guidance.known_evidence,r.conversation_guidance.known_evidence_do_not_reask);});
test('same source facts and action gates in both arms; no owner send grant',()=>{const s=sample();for(const arm of ['on','off']){const r=comparisonResult(toolResult(s,'SEND'),arm);assert.equal(r.sent,false);assert.equal(r.status,'EMAIL_UNAVAILABLE');assert.deepEqual(r.external_actions,[]);assert.equal(s.ownerTest,undefined);}assert.equal(s.intake.handoff,'NOT_REQUESTED');});
test('comparison binding survives existing encryption/reload without parser changes',()=>{const s=sample();s.comparison={experiment:'james-planner-20260929',arm:'off',promptHash:COMMON_PROMPT_HASH};assert.deepEqual(unseal(seal(s,'f'.repeat(64)),s.id,'f'.repeat(64)),s);});
test('private per-arm authorization and expiry are mandatory',()=>{const tokens=JSON.parse(fs.readFileSync(new URL('../.vercel/comparison/owner-access.json',import.meta.url)));assert.equal(authorizeComparison(tokens.on,'on'),'on');assert.equal(authorizeComparison(tokens.off,'off'),'off');assert.throws(()=>authorizeComparison(tokens.on,'off'));assert.throws(()=>authorizeComparison('x'.repeat(43),'on'));assert.throws(()=>authorizeComparison(tokens.on,'on',Date.parse('2026-10-01')));});
test('production never enables comparison',()=>{const old={v:process.env.VERCEL_ENV,c:process.env.JAMES_PLANNER_COMPARISON};try{process.env.VERCEL_ENV='production';process.env.JAMES_PLANNER_COMPARISON='james-planner-20260929';assert.equal(comparisonEnabled(),false);process.env.VERCEL_ENV='preview';assert.equal(comparisonEnabled(),true);}finally{for(const [k,v] of [['VERCEL_ENV',old.v],['JAMES_PLANNER_COMPARISON',old.c]])if(v===undefined)delete process.env[k];else process.env[k]=v;}});
test('common prompt and wait binding fails closed',()=>{const p=JSON.parse(fs.readFileSync(new URL('../.vercel/comparison/baseline.json',import.meta.url)));p.brain.systemPrompt=fs.readFileSync(new URL('../.vercel/comparison/neutral-prompt.txt',import.meta.url),'utf8');assert.equal(sha(p.brain.systemPrompt),COMMON_PROMPT_HASH);checkComparisonPersona(p);p.tools.find(t=>t.name==='james_handoff').awaitResult=false;assert.throws(()=>checkComparisonPersona(p));});
test('instrumentation observes sends; no text injection, SDK upgrade or email authorization',()=>{const ui=fs.readFileSync(new URL('../components/james/JamesCanary.tsx',import.meta.url),'utf8'),trace=fs.readFileSync(new URL('../components/james/comparison-trace.ts',import.meta.url),'utf8');assert.doesNotMatch(ui,/sendUserMessage|sendTalkCommand/);assert.match(trace,/Reflect.apply\(original,this,\[data\]\)/);assert.match(trace,/providerConsumption:'NOT_OBSERVABLE'/);assert.match(ui,/const awaited=chain.current;await awaited/);assert.match(ui,/currentTurnMatches:result.source_turn_id===latestFinalVisitor.current/);});
